# Generated by Django 5.2.6 on 2025-09-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whitelistedip',
            name='ip',
            field=models.CharField(max_length=15),
        ),
    ]
