# Generated by Django 5.2.6 on 2025-09-28 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_blockedip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whitelistedip',
            options={'ordering': ['-date_added'], 'verbose_name': 'IP en Lista Blanca', 'verbose_name_plural': 'IPs en Lista Blanca'},
        ),
        migrations.AlterField(
            model_name='whitelistedip',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelisted_ips', to=settings.AUTH_USER_MODEL, verbose_name='Agregado por'),
        ),
        migrations.AlterField(
            model_name='whitelistedip',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de agregado'),
        ),
        migrations.AlterField(
            model_name='whitelistedip',
            name='ip',
            field=models.GenericIPAddressField(help_text='Dirección IP a incluir en lista blanca', unique=True, verbose_name='Dirección IP'),
        ),
        migrations.AlterField(
            model_name='whitelistedip',
            name='reason',
            field=models.TextField(blank=True, help_text='Razón por la cual se agregó esta IP a la lista blanca', verbose_name='Razón'),
        ),
        migrations.DeleteModel(
            name='BlockedIP',
        ),
    ]
