# Generated by Django 5.2.6 on 2025-10-08 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_alter_whitelistedip_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(help_text='Dirección IP bloqueada', max_length=15, verbose_name='Dirección IP')),
                ('reason', models.TextField(default='Actividad sospechosa', help_text='Razón del bloqueo', verbose_name='Razón')),
                ('blocked_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de bloqueo')),
                ('blocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_ips', to=settings.AUTH_USER_MODEL, verbose_name='Bloqueado por')),
            ],
            options={
                'verbose_name': 'IP Bloqueada',
                'verbose_name_plural': 'IPs Bloqueadas',
                'ordering': ['-blocked_at'],
            },
        ),
    ]
