# Generated by Django 4.2.23 on 2025-08-14 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('frequency', models.CharField(choices=[('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('biannual', 'Semestral'), ('annual', 'Anual')], default='monthly', max_length=20, verbose_name='Frecuencia')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('paused', 'Pausada'), ('cancelled', 'Cancelada'), ('expired', 'Expirada')], default='active', max_length=20, verbose_name='Estado')),
                ('auto_create_expense', models.BooleanField(default=True, verbose_name='Crear Gastos Automáticamente')),
                ('reminder_days', models.IntegerField(default=7, verbose_name='Días de Recordatorio')),
                ('last_renewal_date', models.DateField(blank=True, null=True, verbose_name='Última Renovación')),
                ('next_renewal_validation', models.DateField(blank=True, null=True, verbose_name='Próxima Validación de Renovación')),
                ('renewal_reminder_sent', models.BooleanField(default=False, verbose_name='Recordatorio de Renovación Enviado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.category', verbose_name='Categoría')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.paymentmethod', verbose_name='Método de Pago')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.paymenttype', verbose_name='Tipo de Pago')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'ordering': ['-start_date'],
            },
        ),
    ]
