# Generated by Django 5.2.5 on 2025-08-13 20:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finances', '0003_alter_paymentmethod_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la suscripción')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('frequency', models.CharField(choices=[('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('biannual', 'Semestral'), ('annual', 'Anual')], default='monthly', max_length=20, verbose_name='Frecuencia')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de inicio')),
                ('next_payment_date', models.DateField(verbose_name='Próxima fecha de pago')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('paused', 'Pausada'), ('cancelled', 'Cancelada')], default='active', max_length=20, verbose_name='Estado')),
                ('auto_create_expense', models.BooleanField(default=True, verbose_name='Crear gasto automáticamente')),
                ('reminder_days', models.PositiveIntegerField(default=7, verbose_name='Días de anticipación para recordatorio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances.category', verbose_name='Categoría')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances.paymentmethod', verbose_name='Método de pago')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances.paymenttype', verbose_name='Tipo de pago')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'ordering': ['next_payment_date', 'name'],
            },
        ),
    ]
