# Generated by Django 5.2.6 on 2025-09-19 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0008_expense_finances_ex_user_id_e9b478_idx_and_more'),
        ('subscriptions', '0002_auto_20250814_0038'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-start_date'], 'verbose_name': 'Suscripción', 'verbose_name_plural': 'Suscripciones'},
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='next_payment_date',
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_renewal_date',
            field=models.DateField(blank=True, null=True, verbose_name='Última Renovación'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='next_renewal_validation',
            field=models.DateField(blank=True, null=True, verbose_name='Próxima Validación de Renovación'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='renewal_reminder_sent',
            field=models.BooleanField(default=False, verbose_name='Recordatorio de Renovación Enviado'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='auto_create_expense',
            field=models.BooleanField(default=True, verbose_name='Crear Gastos Automáticamente'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Fin'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.paymentmethod', verbose_name='Método de Pago'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.paymenttype', verbose_name='Tipo de Pago'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='reminder_days',
            field=models.IntegerField(default=7, verbose_name='Días de Recordatorio'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Activa'), ('paused', 'Pausada'), ('cancelled', 'Cancelada'), ('expired', 'Expirada')], default='active', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'status'], name='subscriptio_user_id_2a19e8_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user'], name='subscriptio_user_id_586440_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status'], name='subscriptio_status_5e8870_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['category'], name='subscriptio_categor_24e96b_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['payment_method'], name='subscriptio_payment_ed971d_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['payment_type'], name='subscriptio_payment_bf86ed_idx'),
        ),
    ]
