# Generated by Django 4.2.23 on 2025-08-14 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('icon', models.CharField(default='fas fa-tag', max_length=50, verbose_name='Icono')),
                ('color', models.CharField(default='primary', max_length=20, verbose_name='Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('efectivo', 'EFECTIVO'), ('debito', 'DEBITO'), ('transferencia', 'TRANSFERENCIA'), ('credito', 'CREDITO')], max_length=20, unique=True, verbose_name='Método de Pago')),
                ('icon', models.CharField(default='fas fa-credit-card', max_length=50, verbose_name='Icono')),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('efectivo', 'EFECTIVO'), ('mercado_pago', 'MERCADO PAGO'), ('visa_frances', 'VISA FRANCES'), ('visa_bapro', 'VISA BAPRO'), ('visa_macro', 'VISA MACRO'), ('cuenta_dni', 'CUENTA DNI'), ('transferencia_mp', 'MERCADO PAGO'), ('transferencia_frances', 'FRANCES'), ('transferencia_macro', 'MACRO'), ('transferencia_bapro', 'BAPRO'), ('transferencia_cuenta_dni', 'CUENTA DNI'), ('mastercard_frances', 'MASTERCARD FRANCES'), ('visa_frances_credito', 'VISA FRANCES'), ('visa_bapro_credito', 'VISA BAPRO'), ('mercado_pago_credito', 'MERCADO PAGO')], max_length=50, unique=True, verbose_name='Tipo de Pago')),
                ('is_default', models.BooleanField(default=False, verbose_name='Es por defecto')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.paymentmethod', verbose_name='Método de Pago')),
            ],
            options={
                'verbose_name': 'Tipo de Pago',
                'verbose_name_plural': 'Tipos de Pago',
                'ordering': ['payment_method', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MonthlySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Año')),
                ('month', models.PositiveIntegerField(verbose_name='Mes')),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total gastos')),
                ('total_credit_pending', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total crédito pendiente')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Resumen Mensual',
                'verbose_name_plural': 'Resúmenes Mensuales',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Gasto')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('is_credit', models.BooleanField(default=False, verbose_name='Es un gasto a crédito')),
                ('total_credit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto total del crédito')),
                ('installments', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de cuotas')),
                ('current_installment', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cuota actual')),
                ('remaining_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto restante')),
                ('credit_group_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID del grupo de crédito')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.category', verbose_name='Categoría')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.paymentmethod', verbose_name='Método de Pago')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.paymenttype', verbose_name='Tipo de Pago')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
