# Generated by Django 5.2.5 on 2025-08-13 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_update_payment_structure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['name'], 'verbose_name': 'Método de Pago', 'verbose_name_plural': 'Métodos de Pago'},
        ),
    ]
