# Generated by Django 5.2.5 on 2025-08-13 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_alter_paymentmethod_options'),
        ('finances', '0004_migrate_payment_data'),
    ]

    operations = [
    ]
