# Generated by Django 5.2.5 on 2025-08-13 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_merge_20250813_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='other_payment_method',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='payment_type_new',
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances.paymenttype', verbose_name='Tipo de pago'),
        ),
    ]
