# Generated by Django 5.2.5 on 2025-08-14 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_remove_expense_other_payment_method_and_more'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscription', verbose_name='Suscripción'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='credit_group_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID del grupo de crédito'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='current_installment',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cuota actual'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='installments',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de cuotas'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='is_credit',
            field=models.BooleanField(default=False, verbose_name='Es un gasto a crédito'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre del Gasto'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.paymentmethod', verbose_name='Método de Pago'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.paymenttype', verbose_name='Tipo de Pago'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
    ]
