# Generated by Django 5.2.6 on 2025-09-19 17:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0007_expense_subscription_alter_expense_category_and_more'),
        ('subscriptions', '0002_auto_20250814_0038'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'date'], name='finances_ex_user_id_e9b478_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'is_credit'], name='finances_ex_user_id_ac13bf_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'subscription'], name='finances_ex_user_id_51a84e_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['date'], name='finances_ex_date_81e0d1_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category'], name='finances_ex_categor_19b638_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['payment_method'], name='finances_ex_payment_9ca89f_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['payment_type'], name='finances_ex_payment_4851b5_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['subscription'], name='finances_ex_subscri_0b483b_idx'),
        ),
    ]
