# Generated by Django 5.2.6 on 2025-09-22 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='income',
            new_name='income_inco_user_id_f74de7_idx',
            old_name='income_income_user_id_123456_idx',
        ),
        migrations.RenameIndex(
            model_name='income',
            new_name='income_inco_user_id_327894_idx',
            old_name='income_income_user_id_234567_idx',
        ),
        migrations.RenameIndex(
            model_name='income',
            new_name='income_inco_date_42a611_idx',
            old_name='income_income_date_idx',
        ),
        migrations.RenameIndex(
            model_name='income',
            new_name='income_inco_categor_72aa11_idx',
            old_name='income_income_category_idx',
        ),
        migrations.RenameIndex(
            model_name='income',
            new_name='income_inco_source__66bf60_idx',
            old_name='income_income_source_idx',
        ),
        migrations.RenameIndex(
            model_name='income',
            new_name='income_inco_type_id_a1ca32_idx',
            old_name='income_income_type_idx',
        ),
    ]
