# Generated by Django 5.2.6 on 2025-09-23 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_rename_income_income_user_id_123456_idx_income_inco_user_id_f74de7_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='income',
            name='income_inco_type_id_a1ca32_idx',
        ),
        migrations.RemoveField(
            model_name='income',
            name='type',
        ),
        migrations.AddField(
            model_name='income',
            name='cotizacion_dolar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cotizacion Dólar'),
        ),
        migrations.AddField(
            model_name='income',
            name='en_dolares',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='En Dolares'),
        ),
        migrations.AlterField(
            model_name='incomesource',
            name='name',
            field=models.CharField(choices=[('BZB', 'BZB'), ('Brassara', 'Brassara'), ('Podersa', 'Podersa'), ('Raster', 'Raster'), ('LCC', 'LCC'), ('Sanatorio', 'Sanatorio'), ('Imagenes', 'Imagenes'), ('Sanar', 'Sanar')], max_length=20, unique=True, verbose_name='Source'),
        ),
        migrations.DeleteModel(
            name='IncomeType',
        ),
    ]
