# Generated by Django 5.2.6 on 2025-09-28 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0003_add_dollar_fields'),
    ]

    operations = [
    ]
