# Generated by Django 5.2.5 on 2025-08-13 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finances', '0003_alter_paymentmethod_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del gasto')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto estimado')),
                ('forecast_type', models.CharField(choices=[('subscription', 'Suscripción'), ('credit', 'Crédito'), ('estimated', 'Estimado'), ('recurring', 'Recurrente')], max_length=20, verbose_name='Tipo de estimación')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de finalización')),
                ('frequency', models.CharField(choices=[('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('biannual', 'Semestral'), ('annual', 'Anual'), ('one_time', 'Una vez')], default='monthly', max_length=20, verbose_name='Frecuencia')),
                ('confidence_level', models.PositiveIntegerField(choices=[(10, '10%'), (20, '20%'), (30, '30%'), (40, '40%'), (50, '50%'), (60, '60%'), (70, '70%'), (80, '80%'), (90, '90%'), (100, '100%')], default=80, verbose_name='Nivel de confianza')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances.category', verbose_name='Categoría')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances.paymentmethod', verbose_name='Método de pago')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances.paymenttype', verbose_name='Tipo de pago')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Estimación de Gasto',
                'verbose_name_plural': 'Estimaciones de Gastos',
                'ordering': ['start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Año')),
                ('month', models.PositiveIntegerField(verbose_name='Mes')),
                ('total_forecasted', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total estimado')),
                ('total_subscriptions', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total suscripciones')),
                ('total_credits', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total créditos')),
                ('total_estimated', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total estimado variable')),
            ],
            options={
                'verbose_name': 'Estimación Mensual',
                'verbose_name_plural': 'Estimaciones Mensuales',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
    ]
