# Generated by Django 4.2.23 on 2025-08-14 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='Mes')),
                ('actual_subscriptions', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Suscripciones Reales')),
                ('actual_credits', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Créditos Reales')),
                ('actual_other_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Otros Gastos Reales')),
                ('current_month_estimated', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Estimación del Mes Actual')),
                ('current_month_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Gastos Reales del Mes Actual')),
                ('projected_subscriptions', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Suscripciones Proyectadas')),
                ('projected_credits', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Créditos Proyectados')),
                ('projected_estimates', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Estimaciones Proyectadas')),
                ('total_projected', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Proyectado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Estimación Mensual',
                'verbose_name_plural': 'Estimaciones Mensuales',
                'ordering': ['month'],
                'unique_together': {('month',)},
            },
        ),
        migrations.CreateModel(
            name='ExpenseForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_level', models.DecimalField(decimal_places=2, default=0.5, max_digits=3, verbose_name='Nivel de Confianza')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del gasto')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto estimado')),
                ('expense_type', models.CharField(choices=[('food', 'Comida'), ('health', 'Salud'), ('transport', 'Transporte'), ('entertainment', 'Entretenimiento'), ('utilities', 'Servicios'), ('shopping', 'Compras'), ('other', 'Otros')], default='other', max_length=20, verbose_name='Tipo de Gasto')),
                ('forecast_type', models.CharField(choices=[('subscription', 'Suscripción'), ('credit', 'Crédito'), ('estimated', 'Estimado'), ('recurring', 'Recurrente')], default='estimated', max_length=20, verbose_name='Tipo de estimación')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de finalización')),
                ('frequency', models.CharField(choices=[('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('biannual', 'Semestral'), ('annual', 'Anual'), ('variable', 'Variable')], default='monthly', max_length=20, verbose_name='Frecuencia')),
                ('confidence', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta')], default='medium', max_length=20, verbose_name='Confianza')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('is_automatic_suggestion', models.BooleanField(default=False, verbose_name='Sugerencia Automática')),
                ('suggested_based_on_months', models.IntegerField(default=6, verbose_name='Basado en Últimos Meses')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.category', verbose_name='Categoría')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances.paymentmethod', verbose_name='Método de pago')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances.paymenttype', verbose_name='Tipo de pago')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Estimación de Gasto',
                'verbose_name_plural': 'Estimaciones de Gastos',
                'ordering': ['start_date', 'name'],
            },
        ),
    ]
