# Generated by Django 5.2.5 on 2025-08-14 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0001_initial'),
    ]

    operations = [
    ]
