# Generated by Django 5.2.5 on 2025-08-14 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0002_auto_20250814_0036'),
    ]

    operations = [
    ]
