# Generated by Django 5.2.6 on 2025-09-19 18:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0008_expense_finances_ex_user_id_e9b478_idx_and_more'),
        ('forecasts', '0004_add_user_to_monthlyforecast'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyforecast',
            options={'ordering': ['user', 'month'], 'verbose_name': 'Estimación Mensual', 'verbose_name_plural': 'Estimaciones Mensuales'},
        ),
        migrations.AlterUniqueTogether(
            name='monthlyforecast',
            unique_together={('user', 'month')},
        ),
        migrations.AddField(
            model_name='expenseforecast',
            name='confidence',
            field=models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta')], default='medium', max_length=20, verbose_name='Confianza'),
        ),
        migrations.AddField(
            model_name='expenseforecast',
            name='expense_type',
            field=models.CharField(choices=[('food', 'Comida'), ('health', 'Salud'), ('transport', 'Transporte'), ('entertainment', 'Entretenimiento'), ('utilities', 'Servicios'), ('shopping', 'Compras'), ('other', 'Otros')], default='other', max_length=20, verbose_name='Tipo de Gasto'),
        ),
        migrations.AddField(
            model_name='expenseforecast',
            name='is_automatic_suggestion',
            field=models.BooleanField(default=False, verbose_name='Sugerencia Automática'),
        ),
        migrations.AddField(
            model_name='expenseforecast',
            name='suggested_based_on_months',
            field=models.IntegerField(default=6, verbose_name='Basado en Últimos Meses'),
        ),
        migrations.AddField(
            model_name='monthlyforecast',
            name='actual_credits',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Créditos Reales'),
        ),
        migrations.AddField(
            model_name='monthlyforecast',
            name='actual_other_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Otros Gastos Reales'),
        ),
        migrations.AddField(
            model_name='monthlyforecast',
            name='actual_subscriptions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Suscripciones Reales'),
        ),
        migrations.AddField(
            model_name='monthlyforecast',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
        ),
        migrations.AddField(
            model_name='monthlyforecast',
            name='current_month_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Gastos Reales del Mes Actual'),
        ),
        migrations.AddField(
            model_name='monthlyforecast',
            name='current_month_estimated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Estimación del Mes Actual'),
        ),
        migrations.AddField(
            model_name='monthlyforecast',
            name='projected_credits',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Créditos Proyectados'),
        ),
        migrations.AddField(
            model_name='monthlyforecast',
            name='projected_estimates',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Estimaciones Proyectadas'),
        ),
        migrations.AddField(
            model_name='monthlyforecast',
            name='projected_subscriptions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Suscripciones Proyectadas'),
        ),
        migrations.AddField(
            model_name='monthlyforecast',
            name='total_projected',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Proyectado'),
        ),
        migrations.AddField(
            model_name='monthlyforecast',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Última Actualización'),
        ),
        migrations.AlterField(
            model_name='expenseforecast',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='expenseforecast',
            name='confidence_level',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=3, verbose_name='Nivel de Confianza'),
        ),
        migrations.AlterField(
            model_name='expenseforecast',
            name='forecast_type',
            field=models.CharField(choices=[('subscription', 'Suscripción'), ('credit', 'Crédito'), ('estimated', 'Estimado'), ('recurring', 'Recurrente')], default='estimated', max_length=20, verbose_name='Tipo de estimación'),
        ),
        migrations.AlterField(
            model_name='expenseforecast',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('biannual', 'Semestral'), ('annual', 'Anual'), ('variable', 'Variable'), ('one_time', 'Único')], default='monthly', max_length=20, verbose_name='Frecuencia'),
        ),
        migrations.AlterField(
            model_name='monthlyforecast',
            name='month',
            field=models.DateField(verbose_name='Mes'),
        ),
        migrations.AddIndex(
            model_name='expenseforecast',
            index=models.Index(fields=['user', 'is_active'], name='forecasts_e_user_id_57d12f_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseforecast',
            index=models.Index(fields=['user', 'is_automatic_suggestion'], name='forecasts_e_user_id_5c3b7b_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseforecast',
            index=models.Index(fields=['user', 'start_date'], name='forecasts_e_user_id_5ae334_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseforecast',
            index=models.Index(fields=['user', 'end_date'], name='forecasts_e_user_id_bf1d7a_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseforecast',
            index=models.Index(fields=['category'], name='forecasts_e_categor_dba9ad_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseforecast',
            index=models.Index(fields=['payment_method'], name='forecasts_e_payment_c056cd_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseforecast',
            index=models.Index(fields=['payment_type'], name='forecasts_e_payment_03c2d3_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyforecast',
            index=models.Index(fields=['user', 'month'], name='forecasts_m_user_id_542777_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyforecast',
            index=models.Index(fields=['user'], name='forecasts_m_user_id_b0d620_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyforecast',
            index=models.Index(fields=['month'], name='forecasts_m_month_4a4a28_idx'),
        ),
        migrations.RemoveField(
            model_name='monthlyforecast',
            name='total_credits',
        ),
        migrations.RemoveField(
            model_name='monthlyforecast',
            name='total_estimated',
        ),
        migrations.RemoveField(
            model_name='monthlyforecast',
            name='total_forecasted',
        ),
        migrations.RemoveField(
            model_name='monthlyforecast',
            name='total_subscriptions',
        ),
        migrations.RemoveField(
            model_name='monthlyforecast',
            name='year',
        ),
    ]
