# Generated by Django 5.2.6 on 2025-09-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0006_remove_duplicates_monthlyforecast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyforecast',
            name='projected_credits',
        ),
        migrations.RemoveField(
            model_name='monthlyforecast',
            name='projected_estimates',
        ),
        migrations.RemoveField(
            model_name='monthlyforecast',
            name='projected_subscriptions',
        ),
        migrations.RemoveField(
            model_name='monthlyforecast',
            name='total_projected',
        ),
        migrations.AddField(
            model_name='monthlyforecast',
            name='future_estimated_credits',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Créditos Estimados Futuros'),
        ),
        migrations.AddField(
            model_name='monthlyforecast',
            name='future_estimated_other',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Otros Estimados Futuros'),
        ),
        migrations.AddField(
            model_name='monthlyforecast',
            name='future_estimated_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Estimado Futuro'),
        ),
        migrations.AddField(
            model_name='monthlyforecast',
            name='future_real_credits',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Créditos Reales Futuros'),
        ),
        migrations.AddField(
            model_name='monthlyforecast',
            name='future_real_subscriptions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Suscripciones Reales Futuras'),
        ),
        migrations.AddField(
            model_name='monthlyforecast',
            name='future_real_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Real Futuro'),
        ),
    ]
